---
version: "3"

tasks:

  deploy-nixos:
    desc: Build and deploy nixos configuration using deploy-rs
    silent: true
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - deploy "{{.ROOT_DIR}}/#{{.host}}" --interactive --skip-checks
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which deploy
        msg: "deploy-rs not found"

  .prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?
